domains = [
    "youtube.com",
    "gstatic.com",
    "googletagmanager.com",
    "google-analytics.com",
    "googlesyndication.com",
    "doubleclick.net",
    "googleadservices.com",
    "monday.com",
    "linkedin.com",
    "typekit.net",
    "instagram.com",
    "boxcdn.net",
    "cloudflare.com",
    "cloudflareinsights.com",
    "hotjar.com",
    "facebook.com",
    "asdfinc.io",
    "www.berea.edu",
    "twitter.com",
    "pinterest.com",
    "vimeo.com",
    "spotify.com",
    "slack.com",
    "discord.com",
    "twitch.tv",
    "amazon-adsystem.com",
    "amazon.com",
    "ampproject.org",
    "adservice.google.com",
    "adssettings.google.com",
    "ads.google.com",
    "ad.doubleclick.net",
    "adclick.g.doubleclick.net",
    "securepubads.g.doubleclick.net",
    "pagead2.googlesyndication.com",
    "t.co",
    "bit.ly",
    "tinyurl.com",
    "bootstrapcdn.com",
    "addthis.com",
    "sharethis.com",
    "optimizely.com",
    "quantserve.com",
    "scorecardresearch.com",
    "zedo.com",
    "outbrain.com",
    "taboola.com",
    "yahoo.com",
    "yahoo.net",
    "yimg.com",
    "yahooapis.com",
    "akadns.net",
    "akadns.com",
    "akadns.org",
    "cloudfront.net",
    "amazonaws.com",
    "fbcdn.net",
    "atlassian.com",
    "jetbrains.com",
    "herokuapp.com",
    "salesforce.com",
    "zendesk.com",
    "intercom.io",
    "mailchimp.com",
    "constantcontact.com",
    "getpocket.com",
    "medium.com",
    "quora.com",
    "reddit.com",
    "slideshare.net",
    "scribd.com",
    "weebly.com",
    "wixsite.com",
    "wix.com",
    "tumblr.com",
    "flickr.com",
    "photobucket.com",
    "imgur.com",
    "deviantart.com",
    "behance.net",
    "dribbble.com",
    "codepen.io",
    "jsfiddle.net",
    "stackoverflow.com",
    "github.com",
    "gitlab.com",
    "bitbucket.org",
    "sourceforge.net",
    "npmjs.com",
    "cdnjs.com",
    "unpkg.com",
    "jsdelivr.net",
    "polyfill.io",
    "fonts.googleapis.com",
    "fonts.gstatic.com",
    "use.fontawesome.com",
    "api.github.com",
    "api.twitter.com",
    "api.instagram.com",
    "api.pinterest.com",
    "api.tumblr.com",
    "api.reddit.com",
    "api.medium.com",
    "api.slack.com",
    "api.spotify.com",
    "api.twitch.tv",
    "api.vimeo.com",
    "api.dropboxapi.com",
    "api.cloudflare.com",
    "api.cloudflare.com",
    "energy.gov",
]
urls = [
    "https://www.youtube.com/embed/HTTP/HTTP/HTTP/HTTP/HTTP/HTTP/youtube.com"
]
patterns = [
    ".*embed/HTTP/.*"
]

