# Web Crawler Configuration

[crawler]
#base_url = "https://dkl.cs.arizona.edu/"
#base_url = "https://www2.cs.arizona.edu/classes/cs127b/fall15/"
#base_url = "https://idscan.net/"
base_url = "https://www.tanqueverdeschools.org/"
max_depth = 1000
worker_count = 8
user_agent = "Mozilla/5.0 (compatible; RustCrawler/1.0)"

[network]
request_timeout_ms = 10000

[output]
# Default output directory when using --save without specifying a path
default_save_dir = "output"
