names = [
    'Giovanni Goodall',
    'Ivan Isaman',
    'Tracy Tolentino',
    'Millard Mccain',
    'Jeremy Johnstone',
    'Felix Fusaro',
    'Jefferson Justus',
    'Corey Clegg',
    'Les Labrador',
    'Jerrold Joye',
    'Brent Burt',
    'Nathanael Noyes',
    'Harris Heilmann',
    'Frankie Fabian',
    'Angel Adcox',
    'Perry Plata',
    'Paul Parkins',
    'Willis Wilbourn',
    'Terry Toribio',
    'Jude Jacinto',
    'Stanford Show',
    'Micah Macleod',
    'Matthew Mayen',
    'Enoch Eaton',
    'Erik Eagar',
    'Ricardo Ristow',
    'Dong Deatherage',
    'Gale Goodspeed',
    'Darius Desoto',
    'Nicolas Neff',
    'Xavier Xiong',
    'Haywood Heavener',
    'Winfred Wheeling',
    'Daniel Depuy',
    'Abe Avelar',
    'Major Macken',
    'Elisha Ehlert',
    'Valentine Vicente',
    'Rolf Rudnick',
    'Amado Alan',
    'Ken Kroner',
    'Tyron Thetford',
    'Jorge Joyal',
    'Gustavo Gurule',
    'Julian Jernigan',
    'Jack Jusino',
    'Ollie Oswald',
    'Abraham Armond',
    'Rickie Romanowski',
    'Chester Cramer',
    'Jordon Johson',
    'Jeremiah Jessop',
    'Irving Isaacs',
    'Morgan Mannings',
    'Trenton Troung',
    'Julius Junkins',
    'Brent Byerley',
    'Theo Trabue',
    'Laverne Leonard',
    'Greg Gilreath',
    'Stephan Swint',
    'Wilmer Whitehead',
    'Erich Esquibel',
    'Milan Marco',
    'German Garrido',
    'Edmund Eliason',
    'Elton Eichler',
    'Thomas Tito',
    'Orville Osmond',
    'Brendan Bourbon',
    'Preston Pizer',
    'Kermit Kimsey',
    'Timmy Tubman',
    'Edmond Everhart',
    'Zane Zellner',
    'Sherman Stinson',
    'Jarod Jaworski',
    'Cordell Cole',
    'Dale Dove',
    'Ramon Ridgell',
    'Isiah Irwin',
    'Dino Desjardins',
    'Palmer Pines',
    'Shon Serino',
    'Russ Reichenbach',
    'Kyle Kern',
    'Tod Turner',
    'Brain Bohon',
    'James Judge',
    'Seymour Shoulders',
    'Scott Stefanik',
    'Maximo Meli',
    'Clay Collyer',
    'Michal Mcglade',
    'Adrian Allman',
    'Tommie Tinkham',
    'Tracy Taveras',
    'Lavern Lemmons',
    'Pierre Perret',
    'Wayne Wheeling']

lnf_names = []
for i in names:
    ns = i.split(' ')
    reverse_name = ns[1] + ' ' + ns[0]
    lnf_names.append(reverse_name)

lnf_names.sort()
lnf_names.reverse()
index = 0
for i in range(0, 100, 20):
    print('TA ' + str(index) + ' should grade these students: \n  ', end='')
    for x in range(i, i+20):
        print(lnf_names[x], end=' | ')
    print('\n')



